export const CHANGE_ISFOCUSED_VAL= 'change_isfocused_val'
export const CHANGE_LIST= 'change_list'
export const CHANGE_TotalPage= 'change_totalpage'
export const CHANGE_MOUSEOVER= 'change_mouseover'
export const CHANGE_PAGE= 'change_page'
export const CHANGE_HOME_DATA= 'change_home_data'
export const CHANGE_ARTICLE_LIST= 'change_article_list'
export const CHANGE_GOBACK_SHOW= 'change_goback_show'